---
- name: set user passwords
  hosts: all
  become: yes

  tasks:
  - name: creating password
    user:
      name: kavya-singh
      update_password: always
#      password: "{{ 'abcd123' | crypt('sha512') }}" # this method is not working now
      password: abcd123
